export const MockAnimal = {
  page: {
    pageNumber: 1,
    pageSize: 12,
    numberOfElements: 12,
    totalElements: 563,
    totalPages: 47,
    firstPage: false,
    lastPage: false,
  },
  sort: {
    clauses: [],
  },
  animals: [
    {
      uid: "ANMA0000028271",
      name: "Alvanian cave sloth",
      earthAnimal: false,
      earthInsect: false,
      avian: false,
      canine: false,
      feline: false,
    },
    {
      uid: "ANMA0000010209",
      name: "Alvanian spine mite",
      earthAnimal: false,
      earthInsect: false,
      avian: false,
      canine: false,
      feline: false,
    },
    {
      uid: "ANMA0000028272",
      name: "Alverian dung beetle",
      earthAnimal: false,
      earthInsect: false,
      avian: false,
      canine: false,
      feline: false,
    },
    {
      uid: "ANMA0000199334",
      name: "Ammonite",
      earthAnimal: true,
      earthInsect: false,
      avian: false,
      canine: false,
      feline: false,
    },
    {
      uid: "ANMA0000032373",
      name: "Amphibian",
      earthAnimal: false,
      earthInsect: false,
      avian: false,
      canine: false,
      feline: false,
    },
    {
      uid: "ANMA0000101355",
      name: "Anaconda",
      earthAnimal: true,
      earthInsect: false,
      avian: false,
      canine: false,
      feline: false,
    },
    {
      uid: "ANMA0000028556",
      name: "Andorian bull",
      earthAnimal: false,
      earthInsect: false,
      avian: false,
      canine: false,
      feline: false,
    },
    {
      uid: "ANMA0000005771",
      name: "Andorian redbat",
      earthAnimal: false,
      earthInsect: false,
      avian: false,
      canine: false,
      feline: false,
    },
    {
      uid: "ANMA0000101527",
      name: "Ant",
      earthAnimal: true,
      earthInsect: true,
      avian: false,
      canine: false,
      feline: false,
    },
    {
      uid: "ANMA0000012914",
      name: "Anthropoid ape",
      earthAnimal: false,
      earthInsect: false,
      avian: false,
      canine: false,
      feline: false,
    },
    {
      uid: "ANMA0000188107",
      name: "Apatosaurus",
      earthAnimal: true,
      earthInsect: false,
      avian: false,
      canine: false,
      feline: false,
    },
    {
      uid: "ANMA0000091965",
      name: "Ape",
      earthAnimal: true,
      earthInsect: false,
      avian: false,
      canine: false,
      feline: false,
    },
  ],
};

export const mock = [
  {
    uid: "ANMA0000028271",
    name: "Alvanian cave sloth",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000010209",
    name: "Alvanian spine mite",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000028272",
    name: "Alverian dung beetle",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000199334",
    name: "Ammonite",
    earthAnimal: true,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000032373",
    name: "Amphibian",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000101355",
    name: "Anaconda",
    earthAnimal: true,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000028556",
    name: "Andorian bull",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000005771",
    name: "Andorian redbat",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000101527",
    name: "Ant",
    earthAnimal: true,
    earthInsect: true,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000012914",
    name: "Anthropoid ape",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000188107",
    name: "Apatosaurus",
    earthAnimal: true,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000091965",
    name: "Ape",
    earthAnimal: true,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
];
