export const mock = [
  {
    uid: "ANMA0000032315",
    name: "'Owon",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000264633",
    name: "Abalone",
    earthAnimal: true,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000262167",
    name: "Albatross",
    earthAnimal: true,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000034899",
    name: "Aldebaran mud leech",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000008622",
    name: "Aldebaran serpent",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000010045",
    name: "Aldebaran shellmouth",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000028270",
    name: "Algorian mammoth",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000260398",
    name: "Alien horse",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000027729",
    name: "Alligator",
    earthAnimal: true,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000207062",
    name: "Alopex lagopus",
    earthAnimal: true,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000004117",
    name: "Altarian marsupial",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000264608",
    name: "Altarian spider",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000028271",
    name: "Alvanian cave sloth",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000010209",
    name: "Alvanian spine mite",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000028272",
    name: "Alverian dung beetle",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000199334",
    name: "Ammonite",
    earthAnimal: true,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000032373",
    name: "Amphibian",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000101355",
    name: "Anaconda",
    earthAnimal: true,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000028556",
    name: "Andorian bull",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000005771",
    name: "Andorian redbat",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000101527",
    name: "Ant",
    earthAnimal: true,
    earthInsect: true,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000012914",
    name: "Anthropoid ape",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000188107",
    name: "Apatosaurus",
    earthAnimal: true,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000091965",
    name: "Ape",
    earthAnimal: true,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000284511",
    name: "Aquathawn",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000121552",
    name: "Arabian horse",
    earthAnimal: true,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000025923",
    name: "Arachnid",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000028273",
    name: "Arbazan vulture",
    earthAnimal: false,
    earthInsect: false,
    avian: true,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000020517",
    name: "Arboreal needle snake",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000044740",
    name: "Arctic spider",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000022561",
    name: "Arcturian dog bird",
    earthAnimal: false,
    earthInsect: false,
    avian: true,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000039166",
    name: "Arkarian horn fowl",
    earthAnimal: false,
    earthInsect: false,
    avian: true,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000211503",
    name: "Armadillo",
    earthAnimal: true,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000254549",
    name: "Army ant",
    earthAnimal: true,
    earthInsect: true,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000000111",
    name: "Aurelian",
    earthAnimal: false,
    earthInsect: false,
    avian: true,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000211496",
    name: "Baird's beaked whale",
    earthAnimal: true,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000027506",
    name: "Bajoran bat",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000035446",
    name: "Bajoran shrimp",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000086683",
    name: "Baneriam hawk",
    earthAnimal: false,
    earthInsect: false,
    avian: true,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000041616",
    name: "Bardakian pronghorn moose",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000044739",
    name: "Barrowbug",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000027697",
    name: "Bat",
    earthAnimal: true,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000026290",
    name: "Beagle",
    earthAnimal: true,
    earthInsect: false,
    avian: false,
    canine: true,
    feline: false,
  },
  {
    uid: "ANMA0000053914",
    name: "Bear",
    earthAnimal: true,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000051908",
    name: "Bee",
    earthAnimal: true,
    earthInsect: true,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000080953",
    name: "Beetle",
    earthAnimal: true,
    earthInsect: true,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000272912",
    name: "Beluga whale",
    earthAnimal: true,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000015437",
    name: "Belzoidian flea",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000044424",
    name: "Bengal tiger",
    earthAnimal: true,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: true,
  },
  {
    uid: "ANMA0000224301",
    name: "Berkshire pig",
    earthAnimal: true,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
];

export const mockDetails = [
  {
    uid: "ANMA0000262167",
    name: "Albatross",
    earthAnimal: true,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
];

export const mockTest = [
  {
    uid: "ANMA0000032315",
    name: "'Owon",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000264633",
    name: "Abalone",
    earthAnimal: true,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000262167",
    name: "Albatross",
    earthAnimal: true,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000034899",
    name: "Aldebaran mud leech",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000008622",
    name: "Aldebaran serpent",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000010045",
    name: "Aldebaran shellmouth",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000028270",
    name: "Algorian mammoth",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000260398",
    name: "Alien horse",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000027729",
    name: "Alligator",
    earthAnimal: true,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000207062",
    name: "Alopex lagopus",
    earthAnimal: true,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000004117",
    name: "Altarian marsupial",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
  {
    uid: "ANMA0000264608",
    name: "Altarian spider",
    earthAnimal: false,
    earthInsect: false,
    avian: false,
    canine: false,
    feline: false,
  },
];
